kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: customers-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
      - name: customers
        image: vatsakatta/customers:latest
        ports:
        - containerPort: 8080