kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: customers-deployment
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: customers
      spec:
        containers:
        - name: customers
          image: vatsakatta/customers:latest
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config/customers
          env:
          - name: JAVA_OPTS
            value: -cp /etc/config/customers
        volumes:
        - name: config-volume
          configMap:
            name: shopper-config
            items:
            - key: customers.properties
              path: application.properties
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: orders-deployment
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: orders
      spec:
        containers:
        - name: orders
          image: vatsakatta/orders:latest
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config/orders
          env:
          - name: JAVA_OPTS
            value: -cp /etc/config/orders
        volumes:
        - name: config-volume
          configMap:
            name: shopper-config
            items:
            - key: orders.properties
              path: application.properties
