kind: List
apiVersion: v1
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: customers-service
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      app: customers
    type: NodePort
- kind: Service
  apiVersion: v1
  metadata:
    name: orders-service
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      app: orders
    type: NodePort
- kind: Service
  apiVersion: v1
  metadata:
    name: activemq-service
  spec:
    ports:
    - name: broker
      port: 61616
      targetPort: 61616
    - name: admin
      port: 8161
      targetPort: 8161
    selector:
      app: activemq
    type: NodePort