kind: List
apiVersion: v1
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: customers-service
  spec:
    ports:
    - port: 8081
      targetPort: 8080
    selector:
      app: customers
    type: NodePort
- kind: Service
  apiVersion: v1
  metadata:
    name: orders-service
  spec:
    ports:
    - port: 8082
      targetPort: 8080
    selector:
      app: orders
    type: NodePort