version: '2'
services:
  customers:
    image: vatsakatta/customers
    ports:
    - "8081:8080"
    environment:
    - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
    - SPRING_DATA_MONGODB_HOST=mongodb
  orders:
    image: vatsakatta/orders
    ports:
    - "8082:8080"
    environment:
    - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
  activemq:
    build: activemq
    ports:
    - "8161:8161"
    volumes:
    - /var/log/activemq
    - /var/data/activemq
  mongodb:
    build: mongodb
    ports:
    - "27017:27017"
