kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: activemq-deployment
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: activemq
      spec:
        containers:
        - name: activemq
          image: webcenter/activemq:5.14.2
          ports:
          - name: broker
            containerPort: 61616
          - name: admin
            containerPort: 8161
- kind: Service
  apiVersion: v1
  metadata:
    name: activemq-service
  spec:
    ports:
    - name: broker
      port: 61616
      targetPort: 61616
    - name: admin
      port: 8161
      targetPort: 8161
    selector:
      app: activemq
    type: NodePort